require_relative 'house'
require_relative 'listing_scraper'
require "sqlite3"
require "date"
require 'room'
require 'nokogiri'
require 'open-uri'
require_relative 'formating_module'
require 'sqlite3'
require_relative 'listing_scraper'
